app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

//Login & Logout (Sessions)
Route::get('login', array('before' => 'guest', 'as' => 'session.create', 'uses' => 'SessionsController@create'));
Route::post('sessions', array('before' => 'guest', 'as' => 'session.store', 'uses' => 'SessionsController@store'));
Route::get('logout', array('before' => 'auth', 'uses' => 'SessionsController@destroy'));
Route::delete('sessions/{id}', array('before' => 'auth', 'as' => 'session.destroy', 'uses' => 'SessionsController@destroy'));

//Offers
Route::get('/', array('as' => 'home', 'uses' => 'OffersController@index'));
Route::post('offers/{id}/mail', array('as' => 'offers.postMessage', 'uses' => 'OffersController@postMessage'));
Route::resource('offers', 'OffersController');

//Imprint
Route::get('/latenight', array('as' => 'latenight', 'uses' => 'MiscController@latenight'));

//Contact form
Route::get('/contact', array('as' => 'contact', 'uses' => 'MiscController@contact'));
Route::post('/contact', array('as' => 'contact.postContact', 'uses' => 'MiscController@postContact'));

//Imprint
Route::get('/imprint', array('as' => 'imprint', 'uses' => 'MiscController@imprint'));

//ACP (only used for display)
Route::get('admin', array('before' => 'auth', 'uses' => 'MiscController@acp'));

//Users (only used for database-exchange)
Route::get('users/{id}/edit', array('before' => 'admin', 'as' => 'users.edit', 'uses' => 'UsersController@edit'));
Route::post('users', array('before' => 'admin|csrf', 'as' => 'users.store', 'uses' => 'UsersController@store'));
Route::put('users/{id}', array('before' => 'admin|csrf', 'as' => 'users.update', 'uses' => 'UsersController@update'));
Route::put('users/updatePassword/{id}', array('before' => 'csrf', 'as' => 'users.updatePassword', 'uses' => 'UsersController@updatePassword'));
Route::put('users/updateEmail/{id}', array('before' => 'csrf', 'as' => 'users.updateEmail', 'uses' => 'UsersController@updateEmail'));
Route::put('users/updateLink/{id}', array('before' => 'csrf', 'as' => 'users.updateLink', 'uses' => 'UsersController@updateLink'));
Route::delete('users/{id}', array('before' => 'admin', 'as' => 'users.destroy', 'uses' => 'UsersController@destroy'));

//Categories (only used for database-exchange)
Route::get('categories/{id}/edit', array('before' => 'admin', 'as' => 'categories.edit', 'uses' => 'CategoriesController@edit'));
Route::post('categories', array('before' => 'admin|csrf', 'as' => 'categories.store', 'uses' => 'CategoriesController@store'));
Route::put('categories/{id}', array('before' => 'admin|csrf', 'as' => 'categories.update', 'uses' => 'CategoriesController@update'));
Route::delete('categories/{id}', array('before' => 'admin', 'as' => 'categories.destroy', 'uses' => 'CategoriesController@destroy'));

//Settings (only used for database-exchange)
Route::get('settings/{id}/edit', array('before' => 'admin', 'as' => 'settings.edit', 'uses' => 'SettingsController@edit'));
Route::post('settings', array('before' => 'admin|csrf', 'as' => 'settings.store', 'uses' => 'SettingsController@store'));
Route::put('settings/{id}', array('before' => 'admin|csrf', 'as' => 'settings.update', 'uses' => 'SettingsController@update'));
Route::delete('settings/{id}', array('before' => 'admin', 'as' => 'settings.destroy', 'uses' => 'SettingsController@destroy'));

app/views/frontend/contact.blade.php
@extends('master')
@section('content')
<h3>Kontakt</h3>
<div id="contect">
    <p>Haben Sie Fragen an unseren Webmaster?<br />Schreiben Sie uns doch einfach eine E-Mail!</p>
    {{ Form::open(array('route' => array('contact.postContact')))  }}
        {{ Form::text('name', '', array('class' => 'form-control', 'placeholder' => 'Name'))  }}
        {{ Form::text('email', '', array('class' => 'form-control', 'placeholder' => 'E-Mail Adresse'))  }}
        {{ Form::text('subject', '', array('class' => 'form-control', 'placeholder' => 'Betreff'))  }}
        {{ Form::textarea('message', '', array('class' => 'form-control', 'placeholder' => 'Nachricht'))  }}
        {{ Form::submit('Absenden', array('class' => 'btn btn-primary'))  }}
    {{ Form::close()  }}
</div>
@stop

app/views/frontend/home.blade.php
@extends('master')
@section('content')
<h2>Offener Adventskalender GVV</h2>
<h4>Arbeitsgruppe GVV Knittlingen 2020 </h4>

<p style="text-align: center;"><strong><u>NEU:</u> Besuchen Sie unsere {{ link_to_route('latenight', 'Late-Night Shopping-Aktion') }} am Donnerstag 11. und 18. Dezember 2014 bis 21.00 Uhr</strong></p>

<div id="offers-wrapper">
    <table id="offers" class="table table-striped table-bordered hover" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Firma</th>
                <th>Kategorie</th>
                <th>Name</th>
                <th>Endet am</th>
                <th>Beschreibung</th>
                <th>Preis</th>
                <th>Direktlink</th>
            </tr>
        </thead>

        <tfoot>
            <tr>
                <th>Firma</th>
                <th>Kategorie</th>
                <th>Name</th>
                <th>Endet am</th>
                <th>Beschreibung</th>
                <th>Preis</th>
                <th>Direktlink</th>
            </tr>
        </tfoot>

        <tbody>
            @foreach(Offer::where('startDate', '<=', new DateTime('now'))->where('endDate', '>', new DateTime('now'))->orderBy('id', 'DESC')->get() as $offer)
            <tr>
                <td>{{ link_to($offer->company->website, $offer->company->name, array('target' => '_blank')) }}</td>
                <td>{{ $offer->category->name }}</td>
                <td>{{ $offer->name }}</td>
                <td>{{ date_format(date_create_from_format('Y-m-d H:i:s', $offer->endDate), 'd.m.Y H:i') }} Uhr</td>
                <td>{{ Str::limit(str_replace('&nbsp;', '', filter_var($offer->description, FILTER_SANITIZE_STRING)), 60) }}</td>
                <td>{{ number_format($offer->amount, 2, ',', '.') }}€ inkl. MwSt.</td>
                <td>{{ link_to_route('offers.show', 'Zum Angebot &raquo;', $offer->id, array('class' => 'btn btn-primary')) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@stop

app/views/frontend/imprint.blade.php
@extends('master')
@section('content')
<h3>Impressum</h3>
<div id="imprint">
    <p>
        <b>Gewerbe- und Verkehrsverein Knittlingen</b><br />
        Stuttgarter Str. 53<br />
        75438 Knittlingen<br /><br />
        <b>Telefon:</b> 07043 / 31829<br />
        <b>Telefax:</b> 07043 / 940275<br /><br />
        <b>E-Mail:</b> <a href="mailto:info@gvv-knittlingen.de">info@gvv-knittlingen.de</a><br />
        <b>Internet:</b> <a href="http://www.gvv-knittlingen.de">www.gvv-knittlingen.de</a><br /><br />
        <b>Vorstand:</b> Hagen Jarzambek
    </p>
    <p><strong>Wir möchten Sie darauf hinweisen, dass Ihr Aufenthalt auf dieser Website mittels einer lokal installieren Version von <a href="http://piwik.org/">Piwik</a> getrackt wird.<br/>
    Ihre Daten werden <i>nicht</i> an Dritte weitergegeben und dienen lediglich der Selbstkontrolle über den Erfolg des Projekts. <br/>Wir danken für Ihr Verständnis.</strong></p>
    <p><strong>Hinweis zu allen Links auf dieser Webseite / diesem Server: </strong></p>
    <p>Mit dem Urteil vom 12. Mai 1998 - 312 O 85/98 - "Haftung für Links" hat das Landgericht (LG) Hamburg entschieden, dass man durch die Erstellung eines Links die Inhalte der gelinkten Seite ggf. mit zu verantworten hat. Dies kann - so das Gericht - nur dadurch verhindert werden, dass man sich ausdrücklich von diesen Inhalten distanziert. Da wir Links zu Geschäftspartnern und sonstigen Webseiten oder Servern besitzen - auf dessen Inhalte und Gestaltung wir keinen Einfluss haben - distanzieren wir uns ausdrücklich von sämtlichen Links auf unserer Webseite / unserem Server. Das gilt für alle vorhandenen / kommenden und dagewesenen Links. Wir weisen deshalb darauf hin, dass wir nicht für Inhalte gelinkter Webseiten verantwortlich gemacht werden können.</p>
    <p>Copyright © by Gewerbe- und Verkehrsverein Fauststadt Knittlingen e.V.</p>
    <h4><b>Für Fragen und Anregungen mailen Sie bitte unserem <a href="http://mrauser.net">Webmaster</a>.</b></h4>
    <hr />
    <ul style="padding-left: 0;">
        <li><b>Steuer Nr.:</b> 48050 / 30608</li>
        <li><b>Gerichtsstand:</b> Amtsgericht Maulbronn</li>
        <li><b>Gerichtsregister Nr.:</b> GR 71/02</li>
        <li><b>Vereinsregister Nr.:</b> VR 442</li>
        <li>
            <b>Bankverbindung 1:</b> Sparkasse Pforzheim
            <ul>
                <li><b>BLZ:</b> 666 500 85</li>
                <li><b>Kontonummer:</b> 969 435</li>
            </ul>
        </li>
        <li>
            <b>Bankverbindung 2:</b> Volksbank Pforzheim
            <ul>
                <li><b>BLZ:</b> 666 900 00</li>
                <li><b>Kontonummer:</b> 353 139 7</li>
            </ul>
        </li>
    </ul>
</div>
@stop

app/views/frontend/latenight.blade.php
@extends('master')
@section('content')
<h3>Late-Night Aktion</h3>
<div id="latenight">
    <div id="hidden">
        <h2>Late - Night Shopping am Donnerstag 11. und 18. Dezember 2014 bis 21.00 Uhr</h2>
        <p>
            <strong>Teilnehmende Firmen und Geschäfte</strong>
            <ul>
                <li>Architekt + KFW-Energieberater Hagen Jarzambek</li>
                <li>Bäckerei Reinhardt</li>
                <li>Büro für DVAG Bernd Leger</li>
                <li>Hähnle Geschenk-Küchenbedarf</li>
                <li>Modehaus Scholl</li>
                <li>MRR PC-Service</li>
                <li>Ofelia`s Haar und Nagelstudio</li>
                <li>Optik Weiler</li>
                <li>Ratzefummel Schreiben-Geschenke-Wolle</li>
                <li>Schuhhaus Braun</li>
                <li>Tankhof Kassner</li>
                <li>Weingärtnergenossenschaft Knittlingen</li>
            </ul>
        </p>
    </div>
    
    <img src="/images/latenight.png" alt="Late Night Shopping-Aktion in Knittlingen - Oben genannter Text als Bild" />
</div>
@stop

app/views/frontend/login.blade.php
@extends('master')
@section('content')
<h3>Login</h3>
<p>Bitte geben Sie Ihre Logindaten ein.</p>
{{ Form::open(array('route' => 'session.store', 'class' => 'form-horizontal', 'role' => 'form')) }}
	<div class="form-group">
		{{ Form::label('email', 'E-Mail:', array('class' => 'col-sm-2 control-label')) }}
		<div class="col-sm-10">
			{{ Form::email('email', '', array('class' => 'form-control', 'placeholder' => 'E-Mail Adresse')) }}
		</div>
	</div>

	<div class="form-group">
		{{ Form::label('password', 'Passwort:', array('class' => 'col-sm-2 control-label')) }}
		<div class="col-sm-10">
			{{ Form::password('password', array('class' => 'form-control', 'placeholder' => 'Passwort')) }}
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			{{ Form::submit('Login', array('class' => 'btn btn-default')) }}
		</div>
	</div>
{{ Form::close() }}
@stop

app/views/frontend/offer.blade.php
@extends('master')
@section('content')
<h3>Angebot: {{ $offer->name }}</h3>
<p>{{ $offer->description }}</p>
<p><b>Gültig bis:</b> {{{ date_format(date_create_from_format('Y-m-d H:i:s', $offer->endDate), 'd.m.Y H:i') }}} Uhr</p>
<p><b>Website:</b> {{ link_to($offer->company->website, $offer->company->name, array('target' => '_blank')) }}</p>
<p><b><i>{{{ number_format($offer->amount, 2, ',', '.') }}}€</i></b> inkl. MwSt</p>
<p>{{ link_to(URL::previous(), '&laquo; Zurück', array('class' => 'btn btn-primary')) }}</p>
<hr />
<h3>Schreiben Sie dem Verkäufer eine E-Mail!</h3>
{{ Form::open(array('route' => array('offers.postMessage', Session::get('offerId'))))  }}
    {{ Form::text('name', '', array('class' => 'form-control', 'placeholder' => 'Name'))  }}
    {{ Form::text('email', '', array('class' => 'form-control', 'placeholder' => 'E-Mail Adresse'))  }}
    {{ Form::text('subject', '', array('class' => 'form-control', 'placeholder' => 'Betreff'))  }}
    {{ Form::textarea('message', '', array('class' => 'form-control', 'placeholder' => 'Nachricht'))  }}
    {{ Form::submit('Absenden', array('class' => 'btn btn-primary'))  }}
{{ Form::close()  }}
@stop

app/views/frontend/search.blade.php
@extends('master')
@section('content')
<h3>Angebote durchsuchen</h3>
@stop